language: node_js
node_js:
  - "6.9.2"

branches:
  only:
    - feature/first-tests
    - development

before_script:
  - npm install -g @angular/cli

script:
  - ng test --sm=false --browsers Firefox --single-run=true --watch=false
